i3: update lock scripts

diff --git a/bin/lock b/bin/lock
--- a/bin/lock
+++ b/bin/lock
@@ -1,5 +1,13 @@
 #!/bin/bash
 
-echo "$0: lock at $(date -Is)"
-i3lock -f -c 202020 -i ~/.i3/wallpaper.blured.png
-echo "$0: unlocked at $(date -Is)"
+nofork="--nofork"
+[[ "${1:-}" != "--fork" ]] || nofork=
+
+echo "$0: locking at $(date -Is)"
+
+i3lock $nofork --show-failed-attempts --ignore-empty-password --color=202020 -i ~/.i3/wallpaper.blured.png --tiling || {
+    echo "$0: i3lock failed at $(date -Is)"
+    exit 1
+}
+
+[[ -z "$nofork" ]] || echo "$0: unlocked at $(date -Is)"
diff --git a/bin/slock b/bin/slock
--- a/bin/slock
+++ b/bin/slock
@@ -1,10 +1,19 @@
 #!/bin/bash
 
-#~/bin/purplelock -c xtrlock -i X.X.X.X -a 'pause ?' -l '' &
-~/bin/lock &
-disown
+here="$(cd "$(dirname "$0")"; pwd)"
 
-echo $(date) "## Sleeping ..."
-sleep 1
-sudo pm-suspend
-echo $(date) "## Woke up ..."
+action="${1:-suspend}"
+case "$action" in
+    suspend) ;;
+    hibernate) ;;
+    *)
+        echo "$0: invalid action $action"
+        exit 1
+        ;;
+esac
+
+"$here/lock" --fork || exit 2
+
+echo "$0: $action at $(date -Is)"
+systemctl "$action"
+echo "$0: woke up from $action at $(date -Is)"
